### ISSUE TITLE
Repository not found

### ISSUE THREAD

**Issue by sdorgancs** [Flowm/satvis#2]
Hello,
I try to install satvis but when I ran:
```bash
git submodule update --init
```
I got:
```bash
fatal: repository 'https://github.com/AnalyticalGraphicsInc/cesium-assets.git/' not found
```
The cesium assets repository is now
```bash
https://github.com/AnalyticalGraphicsInc/cesium-assets-list.git
```
instead of 
```bash
https://github.com/AnalyticalGraphicsInc/cesium-assets.git
```

**Comment by Flowm** [comment]
Thanks for the report.

It seems like the cesium-assets repsoitory was deleted by Analytical Graphics.
Unfortunately `cesium-assets-list` is not a replacement as it only contains information about available terrain data, not the Natural Earth II tiled imagery itself.

The `cesium-assets` repository is still referenced in their [Offline-Guide](https://github.com/AnalyticalGraphicsInc/cesium/wiki/Offline-Guide) and there exists [a few forks](https://github.com/Jaca777/cesium-assets/network/members) of it on Github.

For now I updated the submodule url to point to [my own fork](https://github.com/Flowm/cesium-assets) so the `git submodule update --init` should work again.
