### ISSUE TITLE
CesiumSensors.RectangularSensorGraphics的问题

### ISSUE THREAD

**Issue by HuZhuangQiang** [Flowm/satvis#38]
如何 使用new CesiumSensors.RectangularSensorGraphics ()

entity.addProperty("rectangularSensor");

entity.rectangularSensor = new CesiumSensors.RectangularSensorGraphics(
{
xHalfAngle : Cesium.Math.toRadians(40.0),
yHalfAngle : Cesium.Math.toRadians(20.0),
intersectionColor : Cesium.Color.GREEN.withAlpha(0.8),
intersectionWidth : 10,
showIntersection : true,
radius : 1000000.0,
show : true,
showThroughEllipsoid : false
}
);
报错：
![捕获](https://user-images.githubusercontent.com/33933148/64316419-59a6a800-cfe7-11e9-8141-aa348d401af1.PNG)

**Comment by Flowm** [comment]
With the [cesium-sensor-volumes](https://github.com/Flowm/cesium-sensor-volumes) fork I'm using the conic sensor is working fine.
I tried out your code to create a rectangularSensor and while I don't get any crashes the rendering is quite broken.
As I don't use rectangularSensor and don't know enough about the OpenGL Shading Language (GLSL) to debug this, I can't really help you sorry.

<img width="1440" alt="image" src="https://user-images.githubusercontent.com/1117666/64997445-071b9480-d8e1-11e9-8779-5650b2bcf221.png">
