### ISSUE TITLE
can you give a guide to how to wrap in android, I tried cordova, but got black screen with timeline

### ISSUE THREAD

**Issue by riyuezhixing** [Flowm/satvis#39]

**Comment by Flowm** [comment]
I don't have any experience with cordova, but I could imagine that it migh be related to WebGL as the timeline is one of the few elements that are not part of the 3d scene.
Do you see any error messages when loading the application?

**Comment by Flowm** [comment]
Not the approach you are going for, but maybe some additional helpful information:
On a native android app placing a fullscreen android.webkit.WebView that opens the page works quite well as the same thing is happening for the ios app.
An working example for wrapping the app in a webview under android is visible in the meteocool project:
https://github.com/v4lli/meteocool/blob/master/android/app/src/main/java/com/meteocool/MapFragment.kt

Caching most of the application data is handled through [workbox](https://developers.google.com/web/tools/workbox/) (Service Worker framework), so after the initial load most of the files are stored locally and the application is able to run offline.

**Comment by riyuezhixing** [comment]
Maybe it's related to workbox, I just commented the code related to workbox, and it works. Thank you for your kind help.

**Comment by Flowm** [comment]
Glad it works. I guess when you are using cordova the assets would be bundled with the application anyways and you don't need a second layer of cache right?

**Comment by Flowm** [comment]
Glad it works. I assume when you are using cordova the assets would be bundled with the application and you don't need a second layer anyways.
