### ISSUE TITLE
Button tooltipps obscuring other buttons

### ISSUE THREAD

**Issue by v4lli** [Flowm/satvis#47]
![IMG_91BE2D17CA6D-1](https://user-images.githubusercontent.com/1577223/104131238-8a35e900-5375-11eb-80f4-4d619a0511c4.jpeg)

A button's tooltip should probably go away once they button is not tapped any longer.

**Comment by Flowm** [comment]
Unfortunatly there is no convenient touch support in the [Buefy tooltips](https://buefy.org/documentation/tooltip/). Disabled tooltips for devices with no hover capability for now.
