### ISSUE TITLE
轨道

### ISSUE THREAD

**Issue by Mryang123456** [Flowm/satvis#52]
项目运行后没有轨道显示怎么解决

**Comment by dom-robinson** [comment]
The main schedule page shows progress.. Captures are greyed out as they occur. Is that what you wanted?


![Screenshot 2022-04-25 at 09 20 45](https://user-images.githubusercontent.com/30126642/165049326-316bf4eb-d460-4ef8-91a1-18f064c30621.png)

**Comment by Flowm** [comment]
Google translate gives me:
> How to solve the problem that there is no track display after the project is run

I don't quite get what you mean. What "track display" are you referring to?
