### ISSUE TITLE
Hijacked my browser when I'm developing other WebApp use port 8080

### ISSUE THREAD

**Issue by zxj5470** [Flowm/satvis#53]
- **platform**: Windows
- **Browser**: Chrome 100.0; Edge Chromium 100.0

Is there something wrong in `workbox` or other module?

It's what my developing WebApp shows. But shows `Satellite Orbit Visualization` title.

![image](https://user-images.githubusercontent.com/20026798/165033847-a8e81b1a-d413-4822-9762-0b61d1cc799a.png)

![image](https://user-images.githubusercontent.com/20026798/165033545-e3e04f14-2b58-4de2-948f-9e962501e1e4.png)

The same to Chrome browser even though I have cleaned all caches and checked F12 `Network | Disable cache`

**Comment by zxj5470** [comment]
And I find that `curl` is OK, and `IE browser` is "OK" (though I find my app is unsupported but IE shows my App title!)

**Comment by dom-robinson** [comment]
The orbit visualisation (which i think is what is causing your issue) is essentially an iframe from satvis.space. Sometimes it causes problems: You can disable it - it has no effect on the RN2 satellite captures - it was purely added to the display to give you something to look at between passes (and because it looks nice when it works!).

in settings.yml disable 'satvis'

**Comment by zxj5470** [comment]
Run this one in F12 console
```js
navigator.serviceWorker.getRegistrations().then(function(registrations) {
 for(let registration of registrations) {
  registration.unregister()
} })
```

**Comment by Flowm** [comment]
This is an artifact of the service worker managed by workbox. Useful for hosting on a site but not so much for local development. I'll update the service worker init to only run in non-localhost environments.

You already found the solution, but for completeness the service worker can also be removed through the Application tab of the Chrome dev tools:
https://stackoverflow.com/questions/33704791/how-do-i-uninstall-a-service-worker
