### ISSUE TITLE
how to make it move automatically

### ISSUE THREAD

**Issue by watsonnnnn** [Flowm/satvis#55]
how to make it move automatically

**Comment by Flowm** [comment]
What do you want to move automatically?

- If you mean moving the camera automatically: After selecting a satellite you can press the camera icon in the right overlay to focus the satellite and move the camera along with the satellite. This can be triggered on page load by loading with the satellite already selected
- If you mean animating the satellites: There is a clock in the bottom left on desktop that allows increasing the playback time to make the motion of the satellites more visible. This can be triggered on page load with the following js command: `cc.viewer.clockViewModel.multiplier *= 10`
