### ISSUE TITLE
Module not found: Error: Can't resolve 'workbox-routing'

### ISSUE THREAD

**Issue by wangzhanwei666** [Flowm/satvis#56]
ERROR in ./src/sw.js 2:0-48
Module not found: Error: Can't resolve 'workbox-routing' in '/home/xxx/satvis/src'

ERROR in ./src/sw.js 3:0-48
Module not found: Error: Can't resolve 'workbox-strategies' in '/home/xxx/satvis/src'

ERROR in ./src/sw.js 4:0-54
Module not found: Error: Can't resolve 'workbox-expiration' in '/home/xxx/satvis/src'

ERROR in ./src/sw.js 5:0-77
Module not found: Error: Can't resolve 'workbox-precaching' in '/home/xxx/satvis/src'

**Comment by Flowm** [comment]
Can you clarify which command triggers this error?

Just tried the setup on a clean clone and `npm install` followed by `npm run start` is running through without errors.
