### ISSUE TITLE
satellite not coming

### ISSUE THREAD

**Issue by Sharath07SR** [Flowm/satvis#60]
![Capture1](https://user-images.githubusercontent.com/91935397/210367772-c2825682-1cb4-4627-96f3-199584260bbb.JPG)

**Comment by Flowm** [comment]
Hi there,
it looks like you did not download the TLE data which is severed along with the application.
You can do so with `npm run update-tle` as mentioned in the [README.md](https://github.com/Flowm/satvis/blob/next/README.md).

Looking at the blue sphere without texture it looks like you still need to run `git submodule update --init` as well to download the packaged world textures.

Hope this helps!
