### ISSUE TITLE
Module not found: Error: Can't resolve 'cesium-sensor-volumes' in 'E:\node_project\satvis\src\modules'

### ISSUE THREAD

**Issue by BigData-YC** [Flowm/satvis#62]
cesium-sensor-volumes where？？

**Comment by AravindkannanCT** [comment]
@BigData-YC  hi, i have the same issue. were you able to solve this ?

**Comment by Flowm** [comment]
Hi there,
please check the [Development section of the README](https://github.com/Flowm/satvis#development). 

[cesium-sensor-volumes](https://github.com/Flowm/cesium-sensor-volumes) is a submodule that needs to be initialized with `git submodule update --init`.
