### ISSUE TITLE
Module not found: Error: Can't resolve 'Cesium/Core/Cartesian3'

### ISSUE THREAD

**Issue by Noitty** [Flowm/satvis#64]
I executed the npm run build, and 38 errors have came up regarding Cesium. This one is an example:
Module not found: Error: Can't resolve 'Cesium/Core/Cartesian3' in '/home/jarao/GitHub/satvis/node_modules/cesium-sensor-volumes/dist'

I have followed the instructions:
1. git submodule update --init
2. npm install
3. npm run build

Could someone help me?
Thanks,

**Comment by ChristianSchindler** [comment]
I have the same problem did you find a solution ?

**Comment by jonbirge** [comment]
The way to fix this is to change the version of cesium to not allow more than a minor upgrade: change the ^ to a ~ in package.json and it should work. I'd put in a pull request but this doesn't appear to be maintained anymore.

**Comment by rajan1508** [comment]
> The way to fix this is to change the version of cesium to not allow more than a minor upgrade: change the ^ to a ~ in package.json and it should work. I'd put in a pull request but this doesn't appear to be maintained anymore.

It worked for me thanks!!

**Comment by Flowm** [comment]
Hey there,
sry for the long delay I've been busy with other projects for the past half year and only just now finding time to catch up.

Also as noted in the [README](https://github.com/Flowm/satvis/blob/next/README.md) by now please check out the next branch as it contains many improvements over the past done over the past year that I haven't gotten around to fully releasing until now. The dependencies should be fixed there and it is fully compatible with the latest version of CesiumJS.
