### ISSUE TITLE
add LEMUR-2-EMBRIONOVIS to OT TLEs

### ISSUE THREAD

**Issue by martin-dziura-ot** [Flowm/satvis#66]
Add `LEMUR-2-EMBRIONOVIS` to [get-norad.sh#68](https://github.com/Flowm/satvis/blob/ca66bb3c60be2bc1b666ee67814e058d83ca8a45/data/tle/get-norad.sh#L68).

**Comment by Flowm** [comment]
Please check the `next` branch, the handling of these custom satellite visualizations.
https://github.com/Flowm/satvis/blob/next/data/custom/update-custom-data.sh

These TLEs are now maintained in a separate repository:
https://gitlab.com/ororatech/otc/satellite-tle/-/commit/4c08f86760b
