### ISSUE TITLE
Strange problem Globe is gone in Raspi NOAA V2

### ISSUE THREAD

**Issue by edegraaff** [Flowm/satvis#67]
Hi, seems the globe is gone in Raspi Noaa the last version. I see the satelites and tracks and everything but i am not able to get the blue planet visible. No clue what could be the case. Do i miss required comonents or does the pi debian update broke some elements? 

![image](https://github.com/Flowm/satvis/assets/12442749/dfb2e5ce-1068-4b82-bd7f-c21abfce2851)

Does someone has suggestions how to debug?

**Comment by noahwilde** [comment]
Looks like an issue with an API token thats expired/disabled. Console output: 
![image](https://github.com/Flowm/satvis/assets/47438354/dde67528-d027-4593-8f08-18690b1abadb)
Following the link in the error message:
![image](https://github.com/Flowm/satvis/assets/47438354/8efd3ac2-7578-4453-8c5c-d9ae61ea1fff)

See this line:  [         url: "https://api.maptiler.com/tiles/terrain-quantized-mesh/?key=8urAyLJIrn6TeDtH0Ubh",](https://github.com/Flowm/satvis/blob/ca66bb3c60be2bc1b666ee67814e058d83ca8a45/src/modules/CesiumController.js#L213)

**Comment by LloydOS** [comment]
What and where is the file to add the new key on the Raspberry Pi NOAA image?
TIA

**Comment by Flowm** [comment]
Hey there,
sry for the long delay I've been busy with other projects for the past half year and only just now finding time to catch up.

Were you able to resolve the issue? The API key should only be required to show the terrain data which at least in the current version is not enabled by default. The API key is restricted to the https://satvis.space domain, so you would have to create your own (free) account on maptiler and enter the API key there.
