### ISSUE TITLE
No selected satellites on local deployment

### ISSUE THREAD

**Issue by shiroinekotfs** [Flowm/satvis#68]
I recently deployed a local server for this.

However, seems like there are no satellites on the list.

Is there any help? My git repo is here: https://github.com/takinekotfs/SatelliteTracker

![image](https://github.com/Flowm/satvis/assets/115929530/82bb0914-476f-493b-a563-b0839cd7ae21)

**Comment by Flowm** [comment]
Hey there,
sry for the long delay I've been busy with other projects for the past half year and only just now finding time to catch up.

My first supsicion when not seeing any satellites would be that something went wrong with downloading the TLE data. Did you run `npm run update-tle` at least once? The output should look similar to the one below:
<img width="412" alt="image" src="https://github.com/Flowm/satvis/assets/1117666/789ec5aa-3034-4fc0-8174-d76fc1e3968d">

Also as noted in the [README](https://github.com/Flowm/satvis/blob/next/README.md) by now please check out the next branch as it contains many improvements over the past done over the past year that I haven't gotten around to fully releasing until now. Please also try to clone the current state of the repository and check if the display of TLEs works there.

**Comment by shiroinekotfs** [comment]
Closed due I forgot to run the update OwO
