### ISSUE TITLE
Add a geostationary satellite to the list of selectable satellites

### ISSUE THREAD

**Issue by Zerosimi** [Flowm/satvis#69]
The tool offers an immense potential to educate on satellite orbital mechanics. Showing off different types of orbits, by which properties they differ, how they look projected onto 2D vs 3D and so on. 

One thing I am missing is a satellite which is geostationary. So it turns at the same rate as the earth and is therefore always monitoring the same area. It would be helpful for educational purposes as other types of orbits are present. 

As a suggestion for a satellite that is geostationary, one could use the Geostationary Environment Monitoring Spectrometer (GEMS), which was launched in 2020, to monitor air quality over Korea and surrounding countries.

**Comment by Flowm** [comment]
Thanks for the kind words!

I fully agree that having geostationary satellites availabel as well is quite useful to explain orbital mechanics. Please check the latest version of satvis.space available on [satvis.space/next](https://satvis.space/next). As noted in the beginning of the README this version contains lots of improvements including a new default selection of satellites which includes geostationary satellites like the big weather satellites from NOAA, EUMETSAT, JMA.

For explaining GEO satellites and LEO satellites in polar/ SSO orbits I'd also recommend using the inertial references frame, as the camera stays at a fixed position observing the roatating earth. This way you see the GEO satellites moving along with the earth at the same speed and the polar LEO satellites observing a new area each orbit.
https://satvis.space/next/?elements=Point,Label,Orbit&camera=Inertial
